### ISSUE TITLE
[frontend][web]  em safari desktop o banner dos cookies que aparece em cima não desaparece facilmente

### ISSUE THREAD

**Issue by lcfb91** [Tech4covid19/trackovid19-web#216]

**Comment by fabioscsilva** [comment]
I believe this is made on GTM side, not on front end. Can you check it?

**Comment by pfortuna** [comment]
It happens with other browsers too. It's not Safari specific. 
It appears twice, on the landing page and on the login page. Maybe it has to do with being 2 different domains. The script is probably setting a cookie, and since the domain changed, the first cookie is not read on the  login page. 

If this is true, what we should do is figure out if we want to include the script in the two domains, or keep it on just one (perhaps the landing page).

**Comment by skyhorse** [comment]
it was a cookie domain setting issue, the script was not passing the cookie domain properly.
